baseURL = "/"
languageCode = "en-us"
title = "Mike Shade"
theme = "anatole"
summarylength = "10"
enableEmoji = true
enableRobotsTXT = true
paginate = 5
publishDir = "./docs"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  title = "Mike Shade"
  author = "Mike Shade"
  description = "devops and music."
  profilePicture = "https://avatars0.githubusercontent.com/u/393545?s=460&u=97ae867516a23f7aac20cee1ca852ad91e1bf434&v=4"
  displayMode = "dark"

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/mikeshade1"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/mshade"

#[[params.socialIcons]]
#icon = "fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-play"
title = "soundcloud"
url = "https://soundcloud.com/mikeshade"

[menu]

  [[menu.main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "about"
  weight = 300
  identifier = "about"
  url = "/about/"
